config/routes.rb
Park::Application.routes.draw do

  resources :transactions,   :defaults => { :format => 'json' }
  resources :lots,   :defaults => { :format => 'json' }
  resources :parkers,  :defaults => { :format => 'json' }
  resources :merchants,   :defaults => { :format => 'json' }

  

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :lots, dependent: :destroy

  validates_presence_of :firstName
  validates_presence_of :unitnum
  validates_presence_of :street
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :country
  validates_presence_of :phone

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show,  :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    begin
      @merchants = Merchant.where(merchant_params)

      render template: 'merchants/index', status: :ok
    rescue Exception => e
      render json: {:message=> e.to_s}.to_json, status: :not_found
    end
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    begin
      @merchant = Merchant.find(params[:id])
      render template: 'merchants/show',  status: :ok
    rescue Exception => e
      render json: {:message=> e.to_s}.to_json, status: :not_found
    end
  end



  # POST /merchants
  # POST /merchants.json
  def create
    begin
      @merchant = Merchant.create!(merchant_params)
      render template: 'merchants/show', status: :created
    rescue Exception => e
      render json: {:message=> e.to_s}.to_json, status: :internal_server_error
    end

  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.select{|key,value| key.in?(Merchant.column_names())}
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>Listing merchants</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>