config/routes.rb
Park::Application.routes.draw do

  resources :transactions,   :defaults => { :format => 'json' }
  resources :lots,   :defaults => { :format => 'json' }
  resources :parkers,  :defaults => { :format => 'json' }
  resources :merchants,   :defaults => { :format => 'json' }

  

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :parkers, dependent: :destroy
  has_one  :charge, dependent: :destroy
  belongs_to :merchant

  validates_presence_of :unitnum
  validates_presence_of :street
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :country

  geocoded_by :address
  after_validation :geocode

  private
  def address
    [unitnum, street, city, state, country].join(' ')
  end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def index
    begin

      args = params.select{|key,value| key.in?(Lot.column_names())}
      if params.has_key?(:nelat) && params.has_key?(:nelng) && params.has_key?(:swlat) && params.has_key?(:swlng)
        lng = [params[:swlng], params[:nelng]]
        lat = [params[:swlat], params[:nelat]]
        args[:longitude] = lng.min..lng.max
        args[:latitude] = lat.min..lat.max
      end
      if  params.has_key?(:curloc) && params.has_key?(:radius)
        @lots = Lot.where(args).near(params[:curloc], params[:radius])
      else
        @lots = Lot.where(args)
      end
      render template: 'lots/index', status: :ok
    rescue Exception => e
      Rails.logger.error("Encountered an error while indexing  #{e}")
      render json: {:message=> e.to_s}.to_json, status: :not_found
    end
  end
  def create
    begin
      @merchant = Merchant.find(params[:merchant_id])
      @lot = @merchant.lots.create!(params.select{|key,value| key.in?(Lot.column_names())})
      render template: 'lots/show', status: :created
    rescue Exception => e
      render json: {:message=> e.to_s}.to_json, status: :internal_server_error
     # Rails.logger.error("Encountered an error while creating a lot  #{e}")
    end
  end
  def show
    begin
      @lot = Lot.find(params[:id])
      render template: 'lots/show',  status: :ok
    rescue Exception => e
      render json: {:message=> e.to_s}.to_json, status: :not_found
    end
  end

end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Lot", controller: "lots" %>
<%= link_to 'New lot', new_lot_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
  </tr>

  <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.id %></td>
        <td><%= lot.created_at %></td>
        <td><%= link_to 'Show', lots_path %></td>
        <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
        <td><%= link_to 'Destroy', lot_path(lot),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>